### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by airbusa380airplane** [DragonTech26/BDSAddonManager#12]
i got the error 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: The requested operation requires an element of type 'Array', but the target element has type 'String'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonElement.EnumerateArray()
   at AddonManager.JsonParser.ParseManifestJson(String jsonContent, List`1 manifestList)
   at AddonManager.JsonParser.ParseWorldJson()
   at AddonManager.Forms.DirectoryForm.validatePathsButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Private.CoreLib.dll
----------------------------------------
AddonManager
    Assembly Version: 1.0.0.0
    Location: 
    
    i think i did everything right

**Comment by DragonTech26** [comment]
Thanks for the report. Could you please provide the steps to reproduce the issue and upload the manifest.json file that caused the error?
